SPECIAL_DATA_TYPES = {
    'Matrix ID': str,
    'Matrix Tag Comment': str,
    'Matrix Type': str,
    'Diff. Matrix Info.': str,
    'Branch/Terr.': str,
    'Home Branch': str,
    'Bill To ID': str,
    'Customer ID': str,
    'Customer Name': str,
    'Price Class': str,
    'Outside Salesperson': str,
    'Price Line': str,
    'SellGroupAll': str,
    'SellGroupMscAll': str,
    'SellGroupMregAll': str,
    'PROD_NBR': str,
    'Product Description': str,
    'Price Date Ovrd.': str,
    'LIST': float,
    'UMSP': float,
    'CMP': float,
    'STD-COST': float,
    'REP-COST': float,
    'AVG-COST': float,
    'LASTCOST': float,
    'Lnd Cost': float,
    'Avg Lnd': float,
    'Price Basis#': str,
    'Price Formula': str,
    'Qty Break Basis': str,
    'Qty Break Formula': str,
    'Qty Brk. Form Constant': str,
    'Qty Break Points': str,
    'Qty Break UOM': str,
    'Qty Brk. Form Multplier': str,
    'Split Qty': str,
    'Cost Basis#': str,
    'Cost Formula': str,
    'Effective Date': str,
    'Expire Date': str,
}

RATE_CARD_DATA_TYPES = {
    'Matrix ID': str,
    'Customer Number': str,
    'Branch/Terr.': str,
    'Customer Class': str,
    'Price Line': str,
    'Sell Group': str,
    'PROD_NBR': str,
    'Product Description': str,
    'Price Basis#': str,
    'Price Formula': str,
    'Cost Basis#': str,
    'Cost Formula': str,
    'Effective Date': str,
    'Expire Date': str,
}
